language: node_js
node_js:
- '8'
branchs:
  only:
  - master
addons:
  ssh_known_hosts: 47.94.80.19
install:
- npm install &&  npm run build
after_success:
- ssh travis@47.94.80.19 'cd ~/zookdoor/zukboard && git pull'
- ENABLE_NODE_LOG=YES pm2 start ecosystem.config.js --env testing
before_install:
- openssl aes-256-cbc -K $encrypted_3447d4729998_key -iv $encrypted_3447d4729998_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
